BASE_URL = 'https://stellarburgers.nomoreparties.site'
CREATE_USER_ENDPOINT = '/api/auth/register'
AUTH_USER_ENDPOINT = '/api/auth/login'
USER_DATA_ENDPOINT = '/api/auth/user'
DELETE_USER_ENDPOINT = '/api/auth/user'
CREATE_ORDER_ENDPOINT = '/api/orders'
GET_ORDERS_ENDPOINT = '/api/orders'
